### ISSUE TITLE
Switching models error

### ISSUE THREAD

**Issue by dslramsey** [eradicate-dev/eradicateShiny#4]
Switching to a different model type in one of the apps (i.e.  Nmix to REST) triggers an error message.  This is because some model types require extra data to be uploaded but that data can't be uploaded until the model type is itself selected, and the option becomes visible to the user.   I think we need to make sure a particular model isn't fitted until the "fit model" button is pressed.

**Comment by scrogster** [comment]
Now fixed in both eradication and assessment apps by placing isolate() around functions which generate model outputs (AIC, abund_tab(), summary_tab(). Updating of models now explicitly requires pressing the 'Fit model" button again.
